### ISSUE TITLE
Implement feature SLB-F4 (Get all active keepers and them directions)

### ISSUE THREAD

**Issue by NikolayNN** [JujaLabs/keepers-slack-bot#18]
The task will be available after tasks #7 #9 #11
Implement feature SLB-F4
https://github.com/JujaLabs/docs/tree/master/architecture/keepers_slackbot

**Comment by Solykk** [comment]
Эта задача не актуальна для Slack Bot - "KPR-D6 Эту конкретную операцию может выполнять только Система"
