### ISSUE TITLE
Refactoring SlackParsedCommand and SlackNameHandlerService.

### ISSUE THREAD

**Issue by NikolayNN** [JujaLabs/keepers-slack-bot#27]
SlackNameHandlerService and SlackParsedCommand contain dublicate method 
private List<String> getSlackNames() and private List<String> receiveAllSlackNames(String text)
do refactoring

**Comment by ksergey12** [comment]
@NikolayNN @OlgaKulikova For this task I propose to make a duplicate method in SlackParsedCommand static and invoke it from SlackNameHandlerService. I assume that a class SlackParsedCommand will be moved to an external library and further we can replace this invocation with library one.
Is it a proper way or how it could be done better?

**Comment by NikolayNN** [comment]
SlackParsedCommand refactoring to the signature  

public class SlackParsedCommand {
    private UserDTO fromUser;
    private String text;
    private List<String> slackNamesInText;
    private Map<String, UserDTO> usersInText;
    private int userCountInText;

    public SlackParsedCommand(UserDTO fromUser, String text, Map<String, UserDTO> usersInText) {
        this.fromUser = fromUser;
        this.text = text;
        this.usersInText = usersInText;
        slackNamesInText = /*extract from the usersInText list of slackNames*/
        userCountInText = slackNamesInText.size();
    }
